//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompleX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompleX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action was cancelled.
        /// </summary>
        public static string ActionCanceled {
            get {
                return ResourceManager.GetString("ActionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Action is not possible for Current File or Current Content.
        /// </summary>
        public static string ActionNotPossible {
            get {
                return ResourceManager.GetString("ActionNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to current Project &quot;{0}&quot;.
        /// </summary>
        public static string AddToCurrentProject {
            get {
                return ResourceManager.GetString("AddToCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Help: &lt;a href=\&quot;http://www.nksoft.de\&quot;&gt;What happend if I Admin restart?&lt;/a&gt;&quot;.
        /// </summary>
        public static string AdminHelp {
            get {
                return ResourceManager.GetString("AdminHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your first start of CompleX Studio or update. To Update every registration you should start CompleX as Administrator.
        /// </summary>
        public static string AdminRightsFirstStart {
            get {
                return ResourceManager.GetString("AdminRightsFirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After your last startup of CompleX you have added or removed plugins. To Update every registration you should start CompleX as Administrator.
        /// </summary>
        public static string AdminRightsNewPluginsInstalled {
            get {
                return ResourceManager.GetString("AdminRightsNewPluginsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart as Admin.
        /// </summary>
        public static string AdminRightsStartUp {
            get {
                return ResourceManager.GetString("AdminRightsStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to start CompleX Studio as an Administrator.
        /// </summary>
        public static string AdminRightsStartUpDescription {
            get {
                return ResourceManager.GetString("AdminRightsStartUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files.
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anhang_loeschen_16 {
            get {
                object obj = ResourceManager.GetObject("anhang_loeschen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Linked Project (files will not copied).
        /// </summary>
        public static string AsLinkedProject {
            get {
                return ResourceManager.GetString("AsLinkedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Create a Project with linked files. If you add a file to this project, the file will not copied, and stays at the original place. Otherwise all added files will be copied to projectdir with the same structure as your Project..
        /// </summary>
        public static string AsLinkedProjectHint {
            get {
                return ResourceManager.GetString("AsLinkedProjectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this Window as Toolwindow.
        /// </summary>
        public static string AsToolWindow {
            get {
                return ResourceManager.GetString("AsToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to change Password.
        /// </summary>
        public static string ClickToChangePassword {
            get {
                return ResourceManager.GetString("ClickToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ComplexStudio_Desktop_Icon {
            get {
                object obj = ResourceManager.GetObject("ComplexStudio_Desktop_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ComplexStudio_Logo {
            get {
                object obj = ResourceManager.GetObject("ComplexStudio_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Tag.
        /// </summary>
        public static string ConfigureTag {
            get {
                return ResourceManager.GetString("ConfigureTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your Tag Properties here.
        /// </summary>
        public static string ConfigureTagDesc {
            get {
                return ResourceManager.GetString("ConfigureTagDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to rename {0} to {1}?.
        /// </summary>
        public static string Confirm_Rename {
            get {
                return ResourceManager.GetString("Confirm_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Findresults added, would you like to clear old results first?.
        /// </summary>
        public static string ConfirmClearFindResults {
            get {
                return ResourceManager.GetString("ConfirmClearFindResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path(es) to Clipboard.
        /// </summary>
        public static string CopyPathToClipboard {
            get {
                return ResourceManager.GetString("CopyPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cs {
            get {
                object obj = ResourceManager.GetObject("cs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Right Mousebutton.
        /// </summary>
        public static string CtrlRight {
            get {
                return ResourceManager.GetString("CtrlRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Window &quot;{0}&quot; to Toolwindow.
        /// </summary>
        public static string CurrentWindowAsToolWindow {
            get {
                return ResourceManager.GetString("CurrentWindowAsToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*) | *.*.
        /// </summary>
        public static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete all &quot;Dont show again&quot; marks?.
        /// </summary>
        public static string DeleteDsaConfirmation {
            get {
                return ResourceManager.GetString("DeleteDsaConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete File &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteFileConfirmation {
            get {
                return ResourceManager.GetString("DeleteFileConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete File &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteFileQuestion {
            get {
                return ResourceManager.GetString("DeleteFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want delete Layout &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteLayoutShowConfirmation {
            get {
                return ResourceManager.GetString("DeleteLayoutShowConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the Projectnode. Are you sure, you want to delete hole Project?.
        /// </summary>
        public static string DeleteProjectBecauseSelected {
            get {
                return ResourceManager.GetString("DeleteProjectBecauseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteShowConfirmation {
            get {
                return ResourceManager.GetString("DeleteShowConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location or Directory doesn&apos;t exists!.
        /// </summary>
        public static string DirectoryNotExists {
            get {
                return ResourceManager.GetString("DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask me again.
        /// </summary>
        public static string DontAskMeAgian {
            get {
                return ResourceManager.GetString("DontAskMeAgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again.
        /// </summary>
        public static string DsaDefaultText {
            get {
                return ResourceManager.GetString("DsaDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit with {0}.
        /// </summary>
        public static string EditWith {
            get {
                return ResourceManager.GetString("EditWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap einstellungen_16 {
            get {
                object obj = ResourceManager.GetObject("einstellungen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a Item.
        /// </summary>
        public static string EmptyItem {
            get {
                return ResourceManager.GetString("EmptyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Name!.
        /// </summary>
        public static string EmptyItemName {
            get {
                return ResourceManager.GetString("EmptyItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Projectname!.
        /// </summary>
        public static string EmptyProjectName {
            get {
                return ResourceManager.GetString("EmptyProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Projectname!.
        /// </summary>
        public static string EnterProjectName {
            get {
                return ResourceManager.GetString("EnterProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errormessage.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Text or Category empty!.
        /// </summary>
        public static string ErrorToolboxEntryNameOrCategoryEmpty {
            get {
                return ResourceManager.GetString("ErrorToolboxEntryNameOrCategoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no possible Configuration.
        /// </summary>
        public static string Exception_EmptySettingPages {
            get {
                return ResourceManager.GetString("Exception_EmptySettingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group with the Name &quot;{0}&quot; allready exists!.
        /// </summary>
        public static string Exception_GroupAllwaysExists {
            get {
                return ResourceManager.GetString("Exception_GroupAllwaysExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successfully finished!.
        /// </summary>
        public static string ExportDone {
            get {
                return ResourceManager.GetString("ExportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Failed.
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exportieren {
            get {
                object obj = ResourceManager.GetObject("exportieren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exportieren1 {
            get {
                object obj = ResourceManager.GetObject("exportieren1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Tools....
        /// </summary>
        public static string ExternalToolsCaption {
            get {
                return ResourceManager.GetString("ExternalToolsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Connect please check settings for this connection.
        /// </summary>
        public static string FailedToConnect {
            get {
                return ResourceManager.GetString("FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fileDelete_16 {
            get {
                object obj = ResourceManager.GetObject("fileDelete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File always exists.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fileNew_16 {
            get {
                object obj = ResourceManager.GetObject("fileNew_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your first start of CompleX Studio. Would you like to configure recommended Settings now?.
        /// </summary>
        public static string FirstStartWizard {
            get {
                return ResourceManager.GetString("FirstStartWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for new folder.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Explorer.
        /// </summary>
        public static string FtpExplorer {
            get {
                return ResourceManager.GetString("FtpExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all ToolBars.
        /// </summary>
        public static string HideAllToolBars {
            get {
                return ResourceManager.GetString("HideAllToolBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Img1 {
            get {
                object obj = ResourceManager.GetObject("Img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Img2 {
            get {
                object obj = ResourceManager.GetObject("Img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Img28 {
            get {
                object obj = ResourceManager.GetObject("Img28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Img3 {
            get {
                object obj = ResourceManager.GetObject("Img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Img4 {
            get {
                object obj = ResourceManager.GetObject("Img4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Img5 {
            get {
                object obj = ResourceManager.GetObject("Img5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Img6 {
            get {
                object obj = ResourceManager.GetObject("Img6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgCopy {
            get {
                object obj = ResourceManager.GetObject("ImgCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgInfoImage {
            get {
                object obj = ResourceManager.GetObject("ImgInfoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgLargeIcons {
            get {
                object obj = ResourceManager.GetObject("imgLargeIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgLargeIcons1 {
            get {
                object obj = ResourceManager.GetObject("imgLargeIcons1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgOpen {
            get {
                object obj = ResourceManager.GetObject("ImgOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgOpenWindowsFolder {
            get {
                object obj = ResourceManager.GetObject("ImgOpenWindowsFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgSmallIcons {
            get {
                object obj = ResourceManager.GetObject("imgSmallIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgWindows {
            get {
                object obj = ResourceManager.GetObject("ImgWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap importieren {
            get {
                object obj = ResourceManager.GetObject("importieren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap importieren1 {
            get {
                object obj = ResourceManager.GetObject("importieren1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info_24 {
            get {
                object obj = ResourceManager.GetObject("info_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info1 {
            get {
                object obj = ResourceManager.GetObject("info1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert File Content to active File.
        /// </summary>
        public static string InsertFileContent {
            get {
                return ResourceManager.GetString("InsertFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Parameter.
        /// </summary>
        public static string InsertParam {
            get {
                return ResourceManager.GetString("InsertParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Tag.
        /// </summary>
        public static string InsertTag {
            get {
                return ResourceManager.GetString("InsertTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout &quot;{0}&quot; allready exists!
        ///Would you like to replace it?.
        /// </summary>
        public static string LayoutExistsReplaceShowConfirmation {
            get {
                return ResourceManager.GetString("LayoutExistsReplaceShowConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current layout.
        /// </summary>
        public static string LayoutHeader {
            get {
                return ResourceManager.GetString("LayoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Layout.
        /// </summary>
        public static string LoadLayout {
            get {
                return ResourceManager.GetString("LoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap löschen_16 {
            get {
                object obj = ResourceManager.GetObject("löschen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage FTP Accounts.
        /// </summary>
        public static string ManageFtpAccounts {
            get {
                return ResourceManager.GetString("ManageFtpAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minus16 {
            get {
                object obj = ResourceManager.GetObject("minus16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap neues_objekt_16 {
            get {
                object obj = ResourceManager.GetObject("neues_objekt_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thank you.
        /// </summary>
        public static string NoThankYou {
            get {
                return ResourceManager.GetString("NoThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no new Version available to Update!.
        /// </summary>
        public static string NoUpdateAvailable {
            get {
                return ResourceManager.GetString("NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object to insert.
        /// </summary>
        public static string ObjectToInsert {
            get {
                return ResourceManager.GetString("ObjectToInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Default Application.
        /// </summary>
        public static string OpenFileWithDefaultApp {
            get {
                return ResourceManager.GetString("OpenFileWithDefaultApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening files.
        /// </summary>
        public static string OpeningFiles {
            get {
                return ResourceManager.GetString("OpeningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder(s)....
        /// </summary>
        public static string OpenWindowsFolder {
            get {
                return ResourceManager.GetString("OpenWindowsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ordner_16 {
            get {
                object obj = ResourceManager.GetObject("ordner_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; always exists. Would you like to overwrite the existing file?.
        /// </summary>
        public static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page-ID.
        /// </summary>
        public static string PageId {
            get {
                return ResourceManager.GetString("PageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paperbasket.
        /// </summary>
        public static string Paperbasket {
            get {
                return ResourceManager.GetString("Paperbasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password you entered is incorrect.
        /// </summary>
        public static string PasswordWrong {
            get {
                return ResourceManager.GetString("PasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceHolder.
        /// </summary>
        public static string PlaceHolder {
            get {
                return ResourceManager.GetString("PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one of more possible editors/plugins.
        /// </summary>
        public static string PleaseChooseEditor {
            get {
                return ResourceManager.GetString("PleaseChooseEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Connect first to valid server.
        /// </summary>
        public static string PleaseConnectToServer {
            get {
                return ResourceManager.GetString("PleaseConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter a name..
        /// </summary>
        public static string PleaseEnterName {
            get {
                return ResourceManager.GetString("PleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter Serveraddress or IP..
        /// </summary>
        public static string PleaseEnterServer {
            get {
                return ResourceManager.GetString("PleaseEnterServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasde Select a valid Editor.
        /// </summary>
        public static string PleaseSelectEditor {
            get {
                return ResourceManager.GetString("PleaseSelectEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until action is finished!.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until upload is finished.
        /// </summary>
        public static string PleaseWaitWhileUpdate {
            get {
                return ResourceManager.GetString("PleaseWaitWhileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe Version of {0} is not compatible with this Version of CompleX Studio. Do you want to load PlugIn anyway?.
        /// </summary>
        public static string PlugInVersionWrong {
            get {
                return ResourceManager.GetString("PlugInVersionWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versioncheck failed.
        /// </summary>
        public static string PlugInVersionWrongException {
            get {
                return ResourceManager.GetString("PlugInVersionWrongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus16 {
            get {
                object obj = ResourceManager.GetObject("plus16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add File {0} because a file with this Name already exists!.
        /// </summary>
        public static string ProjectExplorerAddExists {
            get {
                return ResourceManager.GetString("ProjectExplorerAddExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleX Studio Projects (*.cspr, *.cslpr) | *.cspr;*.cslpr|CompleX Studio Project Files (*.cspr) | *.cspr|CompleX Studio Linked Project Files (*.cslpr) | *.cslpr.
        /// </summary>
        public static string ProjectFilter {
            get {
                return ResourceManager.GetString("ProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties....
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to export this FTP Settings with password? (If you say &quot;Yes&quot; for security reasons it is requered that you enter password first).
        /// </summary>
        public static string QuestionExportWithPassword {
            get {
                return ResourceManager.GetString("QuestionExportWithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap questionmark {
            get {
                object obj = ResourceManager.GetObject("questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure  to remove all selected Items from Project?.
        /// </summary>
        public static string RemoveFromProjectConfirmation {
            get {
                return ResourceManager.GetString("RemoveFromProjectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove the current password?.
        /// </summary>
        public static string RemoveSettedPassword {
            get {
                return ResourceManager.GetString("RemoveSettedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Value.
        /// </summary>
        public static string ReplacedValue {
            get {
                return ResourceManager.GetString("ReplacedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should restart CompleX to apply your changes. 
        ///Would you like to restart now?.
        /// </summary>
        public static string RestartConfirmation {
            get {
                return ResourceManager.GetString("RestartConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap schliessen_16 {
            get {
                object obj = ResourceManager.GetObject("schliessen_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No possible Files to search.
        /// </summary>
        public static string SearchFilesEmpty {
            get {
                return ResourceManager.GetString("SearchFilesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files with given conditions found!.
        /// </summary>
        public static string SearchResultEmpty {
            get {
                return ResourceManager.GetString("SearchResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Text to Search for.
        /// </summary>
        public static string SearchTextEmpty {
            get {
                return ResourceManager.GetString("SearchTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Tag.
        /// </summary>
        public static string SelectTag {
            get {
                return ResourceManager.GetString("SelectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error via Mail?.
        /// </summary>
        public static string SendThisError {
            get {
                return ResourceManager.GetString("SendThisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Shell Context Menu.
        /// </summary>
        public static string ShellContextMenu {
            get {
                return ResourceManager.GetString("ShellContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all ToolBars.
        /// </summary>
        public static string ShowAllToolBars {
            get {
                return ResourceManager.GetString("ShowAllToolBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ShowConfirmation {
            get {
                return ResourceManager.GetString("ShowConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; is not saved. Would you like to save file first?.
        /// </summary>
        public static string ShowConfirmationCloseSave {
            get {
                return ResourceManager.GetString("ShowConfirmationCloseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Open Files.
        /// </summary>
        public static string SL_AllOpenFiles {
            get {
                return ResourceManager.GetString("SL_AllOpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Document.
        /// </summary>
        public static string SL_CurrentDocument {
            get {
                return ResourceManager.GetString("SL_CurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Project.
        /// </summary>
        public static string SL_CurrentProject {
            get {
                return ResourceManager.GetString("SL_CurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Open Files in Current Project.
        /// </summary>
        public static string SL_OpenFIlesInProject {
            get {
                return ResourceManager.GetString("SL_OpenFIlesInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string SL_Selection {
            get {
                return ResourceManager.GetString("SL_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay on top.
        /// </summary>
        public static string StayOnTop {
            get {
                return ResourceManager.GetString("StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Placeholders.
        /// </summary>
        public static string TestPlaceholders {
            get {
                return ResourceManager.GetString("TestPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars.
        /// </summary>
        public static string Toolbars {
            get {
                return ResourceManager.GetString("Toolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successfully finished.
        /// </summary>
        public static string UpdateFinished {
            get {
                return ResourceManager.GetString("UpdateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading files....
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successfully finished.
        /// </summary>
        public static string UploadFinished {
            get {
                return ResourceManager.GetString("UploadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The following Optionpages couldn&apos;t be saved!.
        /// </summary>
        public static string WariningOptionPages {
            get {
                return ResourceManager.GetString("WariningOptionPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningHeader {
            get {
                return ResourceManager.GetString("WarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Finish&quot; to close the wizard..
        /// </summary>
        public static string WizardClickToFinish {
            get {
                return ResourceManager.GetString("WizardClickToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard is finished.
        /// </summary>
        public static string WizardFinish {
            get {
                return ResourceManager.GetString("WizardFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard successfully finished..
        /// </summary>
        public static string WizardFinishDetail {
            get {
                return ResourceManager.GetString("WizardFinishDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
